name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Format
        run: yarn prettier --check "src/**/*.ts"
      - name: Build
        run: yarn build